name: Run Python 20240526
on:
  push:
jobs:
  build:
    name: run python
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
    - name:Install dependencies
      run: |
        pip3 install --Upgrade pip
    - name: Run python
      run: |
        python3 20240526.py