name: Run Python 20240526
on:
  push: # do this every push
 # schedule:
 # - cron: "0 8 * * *"
jobs:
  build:
    name: set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
    - name: Run python
      run: |
        python3 20240526.py
